text_prompts_2 = [
    "An abstract painting of a futuristic cityscape, with bold colors and distorted shapes",
    "A sculpture of a human figure made entirely out of recycled materials",
    "A digital animation exploring the theme of artificial intelligence and its impact on humanity",
    "A mixed media installation depicting the erosion of natural landscapes due to urbanization",
    "A series of photographs capturing the beauty and diversity of endangered species",
    "A performance art piece that addresses the theme of mental health and self-care",
    "A portrait painting that explores the concept of identity through the use of symbolism",
    "A street art mural that addresses social and political issues in a bold and powerful way",
    "A collage that tells a story of personal journey and self-discovery through found objects",
    "A sound installation that explores the relationship between technology and nature through the use of electronic music and natural sounds",
]

text_prompts = [
    "A whimsical landscape of a fantasy world",
    "A still life of a vase of sunflowers",
    "A portrait of a fierce lion",
    "An abstract painting in the style of Jackson Pollock",
    "A surrealist interpretation of a city skyline",
    "A landscape of a dense jungle",
    "A minimalist rendering of a single apple on a white background",
    "A futuristic cityscape with flying cars",
    "A sea-side village on a stormy night",
    "A portrait of a person with a mysterious expression",
    "A close up of a lady bug resting on a leaf",
    "A street scene in the style of Vincent Van Gogh",
    "A still life of a stack of old books",
    "An abstract geometric painting in bold colors",
    "A black and white photograph of an abandoned building",
    "A landscape of a snowy mountain range",
    "A colorful abstract painting of a city skyline",
    "A detailed portrait of a wolf howling at the moon",
    "A whimsical scene of a mermaid swimming in a lagoon",
    "A minimalist rendering of a cup of coffee on a wooden table",
]
