text_prompts = [
    "A whimsical landscape of a fantasy world",
    "A still life of a vase of sunflowers",
    "A portrait of a fierce lion",
    "An abstract painting in the style of Jackson Pollock",
    "A surrealist interpretation of a city skyline",
    "A landscape of a dense jungle",
    "A minimalist rendering of a single apple on a white background",
    "A futuristic cityscape with flying cars",
    "A sea-side village on a stormy night",
    "A portrait of a person with a mysterious expression",
    "A close up of a lady bug resting on a leaf",
    "A street scene in the style of Vincent Van Gogh",
    "A still life of a stack of old books",
    "An abstract geometric painting in bold colors",
    "A black and white photograph of an abandoned building",
    "A landscape of a snowy mountain range",
    "A colorful abstract painting of a city skyline",
    "A detailed portrait of a wolf howling at the moon",
    "A whimsical scene of a mermaid swimming in a lagoon",
    "A minimalist rendering of a cup of coffee on a wooden table",
]
